version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        patterns: ["*"]
        update-types: ["minor", "patch"]
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        patterns: ["*"]
        update-types: ["minor", "patch"]
