name = "blueskyz-labs-portfolio"
pages_build_output_dir = "./out"
compatibility_date = "2026-08-30"

[vars]
NEXT_PUBLIC_SITE_URL = "https://portfolio.tonydemo.com"
NEXT_PUBLIC_SITE_NAME = "BlueSkyz Labs"
